#!/usr/bin/env python3
"""
Spredd Markets Bot - Interactive Setup Script

Helps configure the bot by generating .env file with required settings.
"""

import os
import secrets
import sys
from pathlib import Path


def print_banner():
    """Print welcome banner."""
    print("""
╔═══════════════════════════════════════════════════════════╗
║                                                           ║
║   🎯 Spredd Markets Bot Setup                             ║
║                                                           ║
║   Multi-platform prediction market trading via Telegram   ║
║   Supports: Kalshi • Polymarket • Opinion Labs            ║
║                                                           ║
╚═══════════════════════════════════════════════════════════╝
    """)


def prompt(message: str, default: str = "", required: bool = False, secret: bool = False) -> str:
    """Prompt user for input."""
    if default:
        display = f"{message} [{default}]: "
    else:
        display = f"{message}: "
    
    while True:
        value = input(display).strip()
        
        if not value and default:
            return default
        
        if not value and required:
            print("  ⚠️  This field is required.")
            continue
        
        return value


def generate_encryption_key() -> str:
    """Generate a secure encryption key."""
    return secrets.token_hex(32)


def main():
    """Run interactive setup."""
    print_banner()
    
    env_path = Path(".env")
    
    if env_path.exists():
        overwrite = prompt("⚠️  .env file already exists. Overwrite? (y/N)", default="n")
        if overwrite.lower() != "y":
            print("\n✅ Setup cancelled. Existing .env preserved.")
            return
    
    print("\n📝 Let's configure your bot...\n")
    print("=" * 50)
    
    # Required settings
    print("\n🔐 REQUIRED SETTINGS\n")
    
    telegram_token = prompt(
        "Telegram Bot Token (from @BotFather)",
        required=True,
        secret=True
    )
    
    database_url = prompt(
        "PostgreSQL Database URL",
        default="postgresql://user:pass@localhost:5432/spredd",
        required=True
    )
    
    # Generate encryption key
    print("\n🔑 Generating encryption key...")
    encryption_key = generate_encryption_key()
    print(f"   Generated: {encryption_key[:8]}...{encryption_key[-8:]}")
    print("   ⚠️  SAVE THIS KEY! Losing it means losing all user wallets!")
    
    # Platform API Keys
    print("\n" + "=" * 50)
    print("\n🏦 PLATFORM API KEYS (optional but recommended)\n")
    
    dflow_api_key = prompt("DFlow API Key (for Kalshi)")
    kalshi_builder_code = prompt("Kalshi Builder Code")
    opinion_api_key = prompt("Opinion Labs API Key")
    
    # RPC URLs
    print("\n" + "=" * 50)
    print("\n🌐 BLOCKCHAIN RPC URLS (press Enter for defaults)\n")
    
    solana_rpc = prompt(
        "Solana RPC URL",
        default="https://api.mainnet-beta.solana.com"
    )
    
    polygon_rpc = prompt(
        "Polygon RPC URL",
        default="https://polygon-bor-rpc.publicnode.com"
    )
    
    bsc_rpc = prompt(
        "BSC RPC URL",
        default="https://bsc-dataseed.binance.org"
    )
    
    # Optional settings
    print("\n" + "=" * 50)
    print("\n⚙️  OPTIONAL SETTINGS\n")
    
    admin_ids = prompt("Admin Telegram IDs (comma-separated)")
    log_level = prompt("Log Level", default="INFO")
    
    # Generate .env file
    print("\n" + "=" * 50)
    print("\n📄 Generating .env file...\n")
    
    env_content = f"""# ===========================================
# Spredd Markets Bot Configuration
# Generated by setup script
# ===========================================

# ===================
# Required Settings
# ===================

TELEGRAM_BOT_TOKEN={telegram_token}
DATABASE_URL={database_url}
ENCRYPTION_KEY={encryption_key}

# ===================
# Platform API Keys
# ===================

DFLOW_API_KEY={dflow_api_key}
KALSHI_BUILDER_CODE={kalshi_builder_code}
OPINION_API_KEY={opinion_api_key}

# ===================
# Blockchain RPCs
# ===================

SOLANA_RPC_URL={solana_rpc}
POLYGON_RPC_URL={polygon_rpc}
BSC_RPC_URL={bsc_rpc}

# ===================
# Optional Settings
# ===================

ADMIN_TELEGRAM_IDS={admin_ids}
LOG_LEVEL={log_level}
MAX_REQUESTS_PER_MINUTE=30
"""
    
    with open(env_path, "w") as f:
        f.write(env_content)
    
    print("✅ .env file created successfully!\n")
    
    # Print next steps
    print("=" * 50)
    print("\n🚀 NEXT STEPS\n")
    print("1. Review .env file and make any adjustments")
    print("2. Ensure PostgreSQL is running")
    print("3. Run the bot:")
    print("   python -m src.main")
    print("")
    print("📚 For more info, see README.md")
    print("")
    print("⚠️  IMPORTANT: Back up your ENCRYPTION_KEY securely!")
    print(f"   Key: {encryption_key}")
    print("")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled.")
        sys.exit(1)
